version: '2'

services:
    node:
        build:
            context: .
            dockerfile: node.dockerfile
        ports:
            - "3000:3000"
        networks:
            - nodeapp-network
    mongodb:
        image: mongo
        ports:
            - "27018:27017"
        networks:
            - nodeapp-network

networks:
    nodeapp-network:
        driver: bridge


